#!/usr/bin/env python3
"""Sync ~/.ssh-manager/.env against IaC sources (homelab-tf + pve-vctcn).

Reads the authoritative VM/host inventory from two repos and rewrites only
the block between BEGIN/END managed markers in mcp-ssh-manager's .env.
Anything outside the markers is preserved verbatim, including blank lines.

Source-of-truth mapping:

  homelab-tf
    Workspace VM YAMLs : {apps,browser,moat,paas,trading,workstation}/vms/<vmid>.yaml
                         filename = vmid, file contains `hostname: <name>`
    PVE host           : 192.168.1.67, hardcoded entry name `pve`

  pve-vctcn
    apps/*/main.tf     : grep `vmid = <N>` + `hostname = "<name>"` inside
                         each `module "vm_<vmid>" { ... }` block. Only
                         three live workspaces today (vctcn-app1, registry,
                         runner) but the regex handles any future vctcn app
                         that follows the same shape
    PVE host           : 192.99.9.212, hardcoded entry name `vctcn-pve`

Only TF-declared resources are managed. Inventory-only hosts (omv, dockge
in `_shared/ansible/inventory.yml`) are deliberately excluded — they are
not TF-authoritative state. Add them by hand below the END marker if you
want them in the MCP.

Hostnames used in the .env follow operator convention:
  - homelab VMs / hosts : <name>.hb.lan (CoreDNS authoritative for hb.lan)
  - vctcn VMs           : <name>.mouriya.lan (netbird mesh DNS)
  - vctcn PVE host      : 192.99.9.212 (not on netbird; raw IP)

CT-side resources are intentionally excluded: per arch invariant, CTs are
reached via `proxmox_pct_remote` (SSH → pve → pct exec), not direct sshd.

Run with no args for a dry-run diff; pass --apply to write.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import difflib
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

HOMELAB_TF = Path(os.environ.get("HOMELAB_TF_DIR", Path.home() / "Ext/code/homelab-tf"))
PVE_VCTCN = Path(os.environ.get("PVE_VCTCN_DIR", Path.home() / "Ext/code/pve-vctcn"))
ENV_FILE = Path(os.environ.get("SSH_MANAGER_ENV", Path.home() / ".ssh-manager/.env"))

BEGIN = "# === BEGIN ssh-mcp-sync managed (regenerated by ~/.claude/skills/ssh-mcp-sync) ==="
END = "# === END ssh-mcp-sync managed ==="

HOMELAB_VM_WORKSPACES = ("apps", "browser", "moat", "paas", "trading", "workstation")


@dataclass(frozen=True)
class Entry:
    key: str          # SSH_SERVER_<KEY>_HOST — uppercase, hyphen-stripped
    host: str         # FQDN or IP
    user: str = "root"
    port: int = 22
    default_dir: str = "/root"
    description: str = ""


def env_key(name: str) -> str:
    """Match the existing .env convention: uppercase, hyphens stripped."""
    return re.sub(r"[^A-Z0-9]", "", name.upper())


def parse_hostname(yaml_path: Path) -> str | None:
    for line in yaml_path.read_text().splitlines():
        m = re.match(r"^\s*hostname\s*:\s*(\S+)", line)
        if m:
            return m.group(1).strip().strip('"').strip("'")
    return None


def homelab_vms() -> list[Entry]:
    out: list[Entry] = []
    for ws in HOMELAB_VM_WORKSPACES:
        vms_dir = HOMELAB_TF / ws / "vms"
        if not vms_dir.is_dir():
            continue
        for yaml in sorted(vms_dir.glob("*.yaml")):
            vmid = yaml.stem
            hostname = parse_hostname(yaml)
            if not hostname:
                print(f"warn: no hostname in {yaml}", file=sys.stderr)
                continue
            out.append(Entry(
                key=env_key(hostname),
                host=f"{hostname}.hb.lan",
                description=f"homelab-tf {ws}/ — VM {vmid} ({hostname})",
            ))
    return out


def vctcn_vms() -> list[Entry]:
    out: list[Entry] = []
    apps = PVE_VCTCN / "apps"
    if not apps.is_dir():
        return []
    for main_tf in sorted(apps.glob("*/main.tf")):
        text = main_tf.read_text()
        # Each VM block: `module "vm_<id>" { ... vmid = N ... hostname = "X" }`.
        # We don't need the full block — vmid and hostname are unique enough
        # within a file given vctcn's one-VM-per-app convention. If that ever
        # changes, this regex needs to scope to the module block.
        for block in re.finditer(
            r'module\s+"vm_(?P<id>\d+)"\s*\{(?P<body>.*?)\n\}',
            text, re.DOTALL,
        ):
            body = block.group("body")
            vmid = block.group("id")
            hostname_m = re.search(r'hostname\s*=\s*"([^"]+)"', body)
            if not hostname_m:
                print(f"warn: no hostname in {main_tf} vm_{vmid}", file=sys.stderr)
                continue
            hostname = hostname_m.group(1)
            workspace = main_tf.parent.name
            out.append(Entry(
                key=env_key(hostname),
                host=f"{hostname}.mouriya.lan",
                description=f"pve-vctcn apps/{workspace}/ — VM {vmid} ({hostname})",
            ))
    return out


def static_hosts() -> list[Entry]:
    return [
        Entry(
            key="PVE",
            host="pve.hb.lan",
            description="homelab Proxmox host (192.168.1.67)",
        ),
        Entry(
            key="VCTCNPVE",
            host="192.99.9.212",
            description="vctcn Proxmox host (OVH, not on netbird mesh)",
        ),
    ]


def render_entry(e: Entry) -> str:
    lines = [
        f"SSH_SERVER_{e.key}_HOST={e.host}",
        f"SSH_SERVER_{e.key}_PORT={e.port}",
        f"SSH_SERVER_{e.key}_USER={e.user}",
        f"SSH_SERVER_{e.key}_DESCRIPTION={e.description}",
        f"SSH_SERVER_{e.key}_DEFAULT_DIR={e.default_dir}",
    ]
    return "\n".join(lines)


def render_managed_block(entries: list[Entry]) -> str:
    seen: set[str] = set()
    deduped: list[Entry] = []
    for e in entries:
        if e.key in seen:
            print(f"warn: duplicate key {e.key} ({e.host}) — keeping first", file=sys.stderr)
            continue
        seen.add(e.key)
        deduped.append(e)
    deduped.sort(key=lambda e: e.key)
    body = "\n\n".join(render_entry(e) for e in deduped)
    return f"{BEGIN}\n{body}\n{END}"


def splice(existing: str, new_block: str) -> str:
    """Replace the existing managed block (or insert one) inside the .env text."""
    if BEGIN in existing and END in existing:
        pattern = re.compile(
            re.escape(BEGIN) + r".*?" + re.escape(END),
            re.DOTALL,
        )
        return pattern.sub(new_block, existing, count=1)
    # First run (no markers). Any pre-existing `SSH_SERVER_*=` line is by
    # definition a server entry — that's the only thing the .env holds — so
    # it belongs in the managed block, not in a "manual" carve-out. Strip
    # those lines; whatever else lives in the file (comments, unrelated env
    # vars) becomes the manual tail.
    surviving = "\n".join(
        line for line in existing.splitlines()
        if not re.match(r"^\s*SSH_SERVER_", line)
    ).strip()
    if surviving:
        return new_block + "\n\n# === manual entries (preserved by ssh-mcp-sync) ===\n" + surviving + "\n"
    return new_block + "\n"


@dataclass(frozen=True)
class ProbeResult:
    entry: Entry
    ok: bool
    detail: str  # short error / success summary


def probe_ssh(entry: Entry, timeout: int = 8) -> ProbeResult:
    """Non-interactively try to SSH in and run `true`.

    Relies on the operator's already-loaded SSH agent (Bitwarden agent on
    this workstation; `SSH_AUTH_SOCK` is inherited from the shell). Uses
    BatchMode to refuse any prompt — password, passphrase, host-key — and
    accept-new so the first contact with a fresh VM auto-trusts its host
    key. StrictHostKeyChecking=accept-new is the standard "TOFU on first
    connection, strict afterward" compromise; it's safe enough for a
    homelab where the operator owns DNS too.
    """
    cmd = [
        "ssh",
        "-o", "BatchMode=yes",
        "-o", f"ConnectTimeout={timeout}",
        "-o", "StrictHostKeyChecking=accept-new",
        "-o", "ServerAliveInterval=0",
        "-p", str(entry.port),
        f"{entry.user}@{entry.host}",
        "true",
    ]
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout + 5,
        )
    except subprocess.TimeoutExpired:
        return ProbeResult(entry, False, f"timeout after {timeout + 5}s")
    except FileNotFoundError:
        return ProbeResult(entry, False, "ssh binary not found")

    if proc.returncode == 0:
        return ProbeResult(entry, True, "ok")
    # Stderr's last non-empty line is usually the most informative one:
    # `ssh: Could not resolve hostname ...`, `Connection timed out`,
    # `Permission denied (publickey)`, `Host key verification failed`.
    err_lines = [l.strip() for l in proc.stderr.splitlines() if l.strip()]
    detail = err_lines[-1] if err_lines else f"exit {proc.returncode}"
    return ProbeResult(entry, False, detail)


def probe_all(entries: list[Entry]) -> list[ProbeResult]:
    """Probe entries in parallel — most of the time is network wait."""
    results: list[ProbeResult] = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(16, max(1, len(entries)))) as pool:
        for r in pool.map(probe_ssh, entries):
            results.append(r)
    return results


def print_probe_summary(results: list[ProbeResult]) -> None:
    width = max((len(r.entry.key) for r in results), default=4)
    for r in sorted(results, key=lambda r: (not r.ok, r.entry.key)):
        marker = "ok  " if r.ok else "FAIL"
        print(f"  [{marker}] {r.entry.key:<{width}}  {r.entry.host:<32}  {r.detail}", file=sys.stderr)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    ap.add_argument("--apply", action="store_true", help="write the file (default: dry-run diff)")
    ap.add_argument("--verify", action="store_true",
                    help="probe SSH login for every rendered entry and exit (no write)")
    ap.add_argument("--skip-verify", action="store_true",
                    help="with --apply, skip the pre-write SSH probe (emergency use)")
    ap.add_argument("--tolerate-failures", action="store_true",
                    help="with --apply, write even if some probes fail (failures still printed)")
    args = ap.parse_args()

    # Only TF-declared resources count. Inventory-driven explicit-ssh hosts
    # (omv, dockge) are deliberately excluded — they aren't built by TF, so
    # they aren't authoritative state. The two PVE hosts are kept because
    # they're the substrate every TF VM runs on (and the target of
    # `pct enter` interactive ops).
    entries = static_hosts() + homelab_vms() + vctcn_vms()

    if args.verify:
        print(f"probing {len(entries)} entries (BatchMode ssh, agent-only auth)...", file=sys.stderr)
        results = probe_all(entries)
        print_probe_summary(results)
        failures = [r for r in results if not r.ok]
        if failures:
            print(f"\n{len(failures)}/{len(results)} unreachable — see above", file=sys.stderr)
            return 1
        print(f"\nall {len(results)} entries reachable", file=sys.stderr)
        return 0

    new_block = render_managed_block(entries)
    existing = ENV_FILE.read_text() if ENV_FILE.is_file() else ""
    new = splice(existing, new_block)

    if existing == new:
        print(f"no changes: {ENV_FILE} already matches IaC ({len(entries)} entries)")
        return 0

    diff = difflib.unified_diff(
        existing.splitlines(keepends=True),
        new.splitlines(keepends=True),
        fromfile=str(ENV_FILE),
        tofile=str(ENV_FILE) + " (proposed)",
    )
    sys.stdout.writelines(diff)

    if not args.apply:
        print(f"\n(dry-run; {len(entries)} managed entries — re-run with --apply to write)", file=sys.stderr)
        return 0

    # --apply: don't write unverified config. Anything else is a footgun —
    # mcp-ssh-manager will happily expose a "server" that times out every
    # call. Default policy is "probe, fail closed".
    if not args.skip_verify:
        print(f"\nprobing {len(entries)} entries before write...", file=sys.stderr)
        results = probe_all(entries)
        print_probe_summary(results)
        failures = [r for r in results if not r.ok]
        if failures and not args.tolerate_failures:
            print(
                f"\nrefusing to write — {len(failures)}/{len(results)} unreachable.\n"
                f"  - if a host is temporarily unreachable, wait or follow authorized recovery; keep valid IaC\n"
                f"  - only confirmed decommissioning warrants removal through the owning IaC workflow\n"
                f"  - if the laptop is off-LAN/off-mesh, run from a host that can reach it\n"
                f"  - to write anyway: --apply --tolerate-failures\n"
                f"  - to skip the probe entirely: --apply --skip-verify",
                file=sys.stderr,
            )
            return 1
        if failures:
            print(f"\n{len(failures)} probe failures tolerated, writing anyway", file=sys.stderr)

    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text(new)
    print(f"\nwrote {ENV_FILE} ({len(entries)} managed entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
